name: Push Configuration

on:
  push:
    branches:
      - qa
      - prod

jobs:
  push-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "TARGET_ORG_ID=${{ vars.TARGET_ORG_ID }}" >> $GITHUB_ENV
          echo "TARGET_API_KEY=${{ vars.TARGET_API_KEY }}" >> $GITHUB_ENV

      - name: Debug environment variables
        run: |
          echo "TARGET_ORG_ID: $TARGET_ORG_ID"
          echo "TARGET_API_KEY: $TARGET_API_KEY"

      - name: Run push_config.py
        run: python push_config.py