name: Push Configuration

on:
  push:
    branches:
      - qa
      - prod
       
jobs:
  push-config:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'prod' && 'prod' || 'qa' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install

      - name: Set environment variables
        run: |
          echo "TARGET_ORG_ID=${{ vars.TARGET_ORG_ID }}" >> $GITHUB_ENV
          echo "TARGET_API_KEY=${{ secrets.TARGET_API_KEY }}" >> $GITHUB_ENV

      - name: Debug environment variables
        run: |
          echo "TARGET_ORG_ID: $TARGET_ORG_ID"
          echo "TARGET_API_KEY: $TARGET_API_KEY"

      - name: Add node_modules/.bin to PATH
        run: echo "$(pwd)/node_modules/.bin" >> $GITHUB_PATH

      - name: Run push_config.py
        run: python push_config.py

      - name: List node_modules/.bin
        run: ls -la node_modules/.bin